alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 20s
      group_interval: 4m
      repeat_interval: 4h
      receiver: 'email-k8s-admin'
      routes: []
    receivers:
    - name: 'email-k8s-admin'
      email_configs:
      - to: 'marco.balamon0506@gmail.com'
        from: 'email-k8s-admin@alertmanager.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'marco.balamon0506@gmail.com'
        auth_password: 'PASSWORD'
        auth_identity: 'marco.balamon0506@gmail.com'
        send_resolved: true
