apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smart-meal-cert
  namespace: istio-system
spec:
  secretName: smart-meal-credential
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: {{ .Values.certificate.domain }}
  dnsNames:
    - {{ .Values.certificate.domain }}
    - "*.{{ .Values.certificate.domain }}"
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer