---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
spec:
  encryptedData:
    SA_PASSWORD: {{ .Values.secret.encryptedPassword }}
  template:
    metadata:
      name: {{ .Values.secret.name }}
      namespace: {{ .Values.secret.namespace }}