apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pvName }}
  labels:
    type: {{ .Values.storage.type }}
spec:
  storageClassName: {{ .Values.storage.class }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  hostPath:
    path: {{ .Values.storage.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
