{{- range .Values.mtls.namespaces }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default
  namespace: {{ . }}
spec:
  host: "*.{{ . }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }} 