{{- range .Values.mtls.namespaces }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ . }}
spec:
  mtls:
    mode: STRICT
{{- end }}

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: sqlserver-permissive
  namespace: 'default'
spec:
  selector:
    matchLabels:
      app: sqlserver
  mtls:
    mode: PERMISSIVE