apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: smart-meal-back-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - microservice-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 7172
            host: smart-meal-back.default.svc.cluster.local
    - match:
        - uri:
            prefix: /swagger
      route:
        - destination:
            port:
              number: 7172
            host: smart-meal-back.default.svc.cluster.local