apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 31433
      protocol: TCP
  selector:
    app: sqlserver