apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
spec:
  encryptedData:
    DB_PASSWORD_SMART_MEAL: "{{ .Values.secrets.keys.DB_PASSWORD_SMART_MEAL }}"
    JWT_TOKEN_KEY: "{{ .Values.secrets.keys.JWT_TOKEN_KEY }}"
    SECRET_STRIPE: "{{ .Values.secrets.keys.SECRET_STRIPE }}"
    SMTP_PASSWORD_SMART_MEAL: "{{ .Values.secrets.keys.SMTP_PASSWORD_SMART_MEAL }}"
  template:
    metadata:
      name: {{ .Values.secrets.name }}
    type: Opaque