apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_PASSWORD_SMART_MEAL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: DB_PASSWORD_SMART_MEAL
            - name: JWT_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: JWT_TOKEN_KEY
            - name: SECRET_STRIPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: SECRET_STRIPE
            - name: SMTP_PASSWORD_SMART_MEAL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: SMTP_PASSWORD_SMART_MEAL
