apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-meal-frontend-deployment
  labels:
    app: smart-meal-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: smart-meal-frontend
  template:
    metadata:
      labels:
        app: smart-meal-frontend
    spec:
      containers:
      - name: smart-meal-frontend-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        {{- range $key, $value := .Values.firebaseSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: firebase-secrets
                key: {{ $key }}
        {{- end }}