apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firebase-secrets
  namespace: default
spec:
  encryptedData:
    FIREBASE_API_KEY: {{ .Values.firebaseSecrets.FIREBASE_API_KEY }}
    FIREBASE_APP_ID: {{ .Values.firebaseSecrets.FIREBASE_APP_ID }}
    FIREBASE_AUTH_DOMAIN: {{ .Values.firebaseSecrets.FIREBASE_AUTH_DOMAIN }}
    FIREBASE_MEASUREMENT_ID: {{ .Values.firebaseSecrets.FIREBASE_MEASUREMENT_ID }}
    FIREBASE_MESSAGING_SENDER_ID: {{ .Values.firebaseSecrets.FIREBASE_MESSAGING_SENDER_ID }}
    FIREBASE_PROJECT_ID: {{ .Values.firebaseSecrets.FIREBASE_PROJECT_ID }}
    FIREBASE_STORAGE_BUCKET: {{ .Values.firebaseSecrets.FIREBASE_STORAGE_BUCKET }}